# Generated by Django 4.1.6 on 2023-02-14 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolcre', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
